### ISSUE TITLE
Excessive Spawns

### ISSUE THREAD

**Issue by WenXin20** [Coda1552/BabyFat#3]
Minecraft v1.19.2
Forge v43.1.47
Baby Fat v1.1.0
- Ranchu seem to have no spawn cap and is bringing the game down to 2 fps for me

![image](https://user-images.githubusercontent.com/12000593/199404757-d0ae6de1-0c1b-44e4-9ad0-9c38c9f3789f.png)![image](https://user-images.githubusercontent.com/12000593/199405248-d341eee3-b317-4439-a458-9c36b59df40a.png)

**Comment by WenXin20** [comment]
Oh my, this is after the server ran all night

![image](https://user-images.githubusercontent.com/12000593/199499574-5d29f26e-318c-481c-a7ed-58a0c8032032.png)

`/kill` killed 2999 ranchu's

**Comment by JonahFuses** [comment]
hello! THe latest release should have this all sorted! Sorry for the inconvenience!

**Comment by WenXin20** [comment]
Thanks!
